version: '3.8'
services:
  job-portal-service:
    container_name: job-portal-service
    build: ../
    environment:
      SPRING_DATASOURCE_URL: ${JOB_PORTAL_POSTGRES_DATABASE_URL}
      SPRING_DATASOURCE_USERNAME: ${JOB_PORTAL_POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${JOB_PORTAL_POSTGRES_PASSWORD}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
    ports:
      - "8082:8080"
    volumes:
      - .:/app
    depends_on:
      - job-portal-service-postgres
    networks:
      - job-portal-postgres-network
      - job-portal-keycloak-network
  job-portal-service-postgres:
    container_name: job-portal-service-postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: ${JOB_PORTAL_POSTGRES_USER}
      POSTGRES_PASSWORD: ${JOB_PORTAL_POSTGRES_PASSWORD}
      POSTGRES_DB: ${JOB_PORTAL_POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - pg-data:/var/lib/postgresql
    restart: always
    networks:
      - job-portal-postgres-network
  job-portal-keycloak-postgres:
    image: postgres:latest
    container_name: job-portal-keycloak-postgres
    environment:
      POSTGRES_USER: ${KEYCLOAK_DB_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      POSTGRES_DB: ${KEYCLOAK_DB}
    ports:
      - "5436:5432"
    volumes:
      - job_portal_keycloak_data:/var/keycloak/data
    restart: always
    networks:
      - job-portal-keycloak-network
  job-portal-keycloak:
    container_name: job-portal-keycloak
    image: quay.io/keycloak/keycloak:latest
    environment:
      KC_DB: postgres
      KC_DB_URL: ${KEYCLOAK_DB_URL}
      KC_DB_USERNAME: ${KEYCLOAK_DB_USER}
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KC_LOG_LEVEL: info
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    command: ["start-dev"]
    ports:
      - "8080:8080"
    depends_on:
      - job-portal-service-postgres
    networks:
      - job-portal-keycloak-network
      - job-portal-postgres-network
networks:
  job-portal-postgres-network:
  job-portal-keycloak-network:
volumes:
  pg-data:
  job_portal_keycloak_data: