version: '3.8'
services:
  job-portal-service:
    build: ../
    container_name: job-portal-service
    ports:
      - "8081:8081"
    volumes:
      - .:/app
    depends_on:
      - postgres
    networks:
      - job-portal-postgres-network
      - keycloak-network
  postgres:
    image: postgres:latest
    container_name: job-portal-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5433"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - pg-data:/var/lib/postgresql
    restart: always
    networks:
      - job-portal-postgres-network
networks:
  job-portal-postgres-network:
  keycloak-network:
volumes:
  pg-data: